### ISSUE TITLE
Docker build failing at "git remote add origin" step

### ISSUE THREAD

**Issue by answerquest** [fholzer/docker-nginx-brotli#90] opened 2023-04-22 13:54 UTC
I cloned this repo to my local, got the terminal into the repo folder and ran this command:
```
docker build -t nginx-brotli-server . 
```

And it errored out here:

```bash
tep 14/31 : RUN 	mkdir -p /usr/src/ngx_brotli 	&& cd /usr/src/ngx_brotli 	&& git init 	&& git remote add origin https://github.com/google/ngx_brotli.git 	&& git fetch --depth 1 origin $NGX_BROTLI_COMMIT 	&& git checkout --recurse-submodules -q FETCH_HEAD 	&& git submodule update --init --depth 1 	&& cd .. 	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz 	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc         && sha512sum nginx.tar.gz nginx.tar.gz.asc 	&& export GNUPGHOME="$(mktemp -d)" 	&& gpg --import /tmp/gpg/* 	&& gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz 	&& mkdir -p /usr/src 	&& tar -zxC /usr/src -f nginx.tar.gz
 ---> Running in 0713b66bffd1
+ mkdir -p /usr/src/ngx_brotli
+ cd /usr/src/ngx_brotli
+ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /usr/src/ngx_brotli/.git/
+ git remote add origin https://github.com/google/ngx_brotli.git
+ git fetch --depth 1 origin 6e975bcb015f62e1f303054897783355e2a877dc
fatal: unable to access 'https://github.com/google/ngx_brotli.git/': Could not resolve host: github.com
The command '/bin/bash -x -c mkdir -p /usr/src/ngx_brotli 	&& cd /usr/src/ngx_brotli 	&& git init 	&& git remote add origin https://github.com/google/ngx_brotli.git 	&& git fetch --depth 1 origin $NGX_BROTLI_COMMIT 	&& git checkout --recurse-submodules -q FETCH_HEAD 	&& git submodule update --init --depth 1 	&& cd .. 	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz 	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc         && sha512sum nginx.tar.gz nginx.tar.gz.asc 	&& export GNUPGHOME="$(mktemp -d)" 	&& gpg --import /tmp/gpg/* 	&& gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz 	&& mkdir -p /usr/src 	&& tar -zxC /usr/src -f nginx.tar.gz' returned a non-zero code: 128
```

**Comment by fholzer** [comment] 2023-04-22 18:33
This looks like an issue with your network or docker setup. Not an issue with the Dockerfile or this repo. Can you describe your setup?
What OS/distro you're running docker on?
Is it virtualized? If so, how? (WSL?)

**Comment by answerquest** [comment] 2023-04-23 14:53
Hi @fholzer, thank you for the quick response.

I'm on a Linux Mint 21.1 Cinnamon OS, 64bit, AMD Ryzen 5 5625U laptop.
Have been git-cloning github and docker repos, images etc all this time and not facing any issue. Have seen git clone command working inside a docker build as well.

I'm suspecting it's these advanced steps of git init + remote add + fetch instead of a straightforward git clone that are causing problem. Will try some alternative way later on. For now I've gotten a working nginx container with gzip compression and am using that, so might be some time before I get back to this.

**Comment by fholzer** [comment] 2023-04-24 14:22
Well, FWIW, based on the error message `Could not resolve host: github.com` it very much looks like a DNS issue. There's several issues related to this in docker and related github repos, and on the internet in general: https://www.google.com/search?q=docker+build+dns+%22failure+resolving%22+OR+%22Could+not+resolve+host%22

**Comment by fholzer** [comment] 2023-05-04 17:49
Closing this, as it's most likely a DNS issue related with your docker/system setup. Feel free to re-open if you found a solution and think the issue is with the Dockerfile.

**Closed by fholzer** 2023-05-04 17:49 UTC
